import { Hono } from 'hono';
import type { PostgrestError } from '@supabase/supabase-js';
import { z } from 'zod';
import { createAdminClient } from '../lib/supabase';
import { requireAuth } from '../middleware/auth';
import { hasPermission } from '../middleware/permission';
import { writeAuditLog } from '../services/auditService';
import { ATTACHMENTS_BUCKET } from '../services/storageService';
import { TICKET_SIGNATURE_BUCKET } from '../services/ticketSignatureService';
import type { AppEnv } from '../types';
import { dbFailJson } from '../utils/dbError';
import { fail, ok } from '../utils/response';

type DeleteMode = 'hard' | 'soft' | 'archive';

interface DeletionResource {
  table: string;
  permission: string;
  module: string;
  mode?: DeleteMode;
  protectedFlag?: string;
}

/**
 * Explicit allowlist for row deletion. The client can only select one of these logical names;
 * it can never submit a database table or permission key directly.
 *
 * Immutable ledgers (audit/login logs, movements, histories, exports and notifications) are
 * deliberately absent. They are evidence generated by the system, not user-managed records.
 */
const DELETION_RESOURCES = {
  'access-requests': { table: 'access_requests', permission: 'access_request.process', module: 'access-request' },
  'access-registry': { table: 'user_access_registry', permission: 'access_registry.manage', module: 'access-registry' },
  'access-systems': { table: 'access_systems', permission: 'access_system.manage', module: 'access-system' },
  'approval-groups': { table: 'approval_groups', permission: 'approval_group.manage', module: 'approval-group' },
  'asset-categories': { table: 'asset_categories', permission: 'asset_category.manage', module: 'asset-category' },
  assets: { table: 'assets', permission: 'asset.dispose', module: 'asset' },
  'backup-logs': { table: 'backup_logs', permission: 'backup.manage', module: 'backup', mode: 'archive' },
  'bcp-plans': { table: 'bcp_plans', permission: 'backup.manage', module: 'backup', mode: 'archive' },
  'cause-codes': { table: 'ticket_cause_codes', permission: 'cause_code.manage', module: 'cause-code' },
  changes: { table: 'change_requests', permission: 'change.approve', module: 'change', mode: 'archive' },
  'ci-relationships': { table: 'ci_relationships', permission: 'cmdb.manage', module: 'cmdb' },
  'configuration-items': { table: 'configuration_items', permission: 'cmdb.manage', module: 'cmdb' },
  contracts: { table: 'contracts', permission: 'contract.manage', module: 'contract' },
  departments: { table: 'departments', permission: 'department.manage', module: 'department' },
  'employee-assignments': { table: 'employee_assignments', permission: 'employee.manage', module: 'employee-assignment' },
  employees: { table: 'employees', permission: 'employee.manage', module: 'employee' },
  'form-templates': { table: 'form_templates', permission: 'form.manage', module: 'form' },
  incidents: { table: 'incidents', permission: 'incident.manage', module: 'incident', mode: 'archive' },
  'inventory-items': { table: 'inventory_items', permission: 'inventory.manage', module: 'inventory' },
  'issue-forms': { table: 'issue_forms', permission: 'form.manage', module: 'form' },
  'line-links': { table: 'line_users', permission: 'line.manage', module: 'line' },
  'log-reviews': { table: 'log_reviews', permission: 'monitoring.manage', module: 'monitoring', mode: 'archive' },
  'logging-systems': { table: 'logging_systems', permission: 'monitoring.manage', module: 'monitoring', mode: 'archive' },
  'known-errors': { table: 'known_errors', permission: 'problem.manage', module: 'problem' },
  'maintenance-plans': { table: 'maintenance_plans', permission: 'maintenance.manage', module: 'maintenance' },
  positions: { table: 'positions', permission: 'position.manage', module: 'position' },
  problems: { table: 'problems', permission: 'problem.manage', module: 'problem' },
  'recovery-tests': { table: 'recovery_tests', permission: 'backup.manage', module: 'backup', mode: 'archive' },
  roles: { table: 'roles', permission: 'role.manage', module: 'role', protectedFlag: 'is_system' },
  'service-catalog': { table: 'service_catalog', permission: 'service_catalog.manage', module: 'service-catalog' },
  'service-requests': { table: 'service_requests', permission: 'service_request.close', module: 'service-request' },
  'software-licenses': { table: 'software_licenses', permission: 'license.manage', module: 'license' },
  'ticket-categories': { table: 'ticket_categories', permission: 'ticket_category.manage', module: 'ticket-category', protectedFlag: 'is_security_default' },
  tickets: { table: 'tickets', permission: 'ticket.close', module: 'ticket', mode: 'soft' },
  vendors: { table: 'vendors', permission: 'vendor.manage', module: 'vendor' },
  vulnerabilities: { table: 'vulnerability_findings', permission: 'vulnerability.manage', module: 'vulnerability' },
  'workflow-definitions': { table: 'workflow_definitions', permission: 'workflow.manage', module: 'workflow', mode: 'archive' },
  'workflow-instances': { table: 'workflow_instances', permission: 'workflow.manage', module: 'workflow', mode: 'archive' },
} as const satisfies Record<string, DeletionResource>;

export type DeletionResourceName = keyof typeof DELETION_RESOURCES;

export function getDeletionResource(name: string): DeletionResource | undefined {
  return Object.prototype.hasOwnProperty.call(DELETION_RESOURCES, name)
    ? DELETION_RESOURCES[name as DeletionResourceName]
    : undefined;
}

export const deletionResourceNames = Object.freeze(Object.keys(DELETION_RESOURCES));

const idSchema = z.string().uuid();
export const deletionReasonSchema = z.object({
  reason: z.string().trim().min(3).max(1000),
}).strict();

/** PostgREST caps one response and truncates silently, so every lookup below reads page by page. */
const STORAGE_LOOKUP_PAGE_SIZE = 1000;
/** Keeps the `target_id=in.(...)` filter well inside the URL length a Worker fetch will accept. */
const STORAGE_LOOKUP_ID_BATCH = 100;

interface LineTicketPathRow {
  id: string;
  signature_storage_path: string | null;
  requester_signature_storage_path: string | null;
}

async function readAllPages<T>(
  readPage: (from: number, to: number) => PromiseLike<{ data: T[] | null; error: PostgrestError | null }>,
): Promise<{ rows: T[] } | { error: PostgrestError }> {
  const rows: T[] = [];
  for (let from = 0; ; from += STORAGE_LOOKUP_PAGE_SIZE) {
    const { data, error } = await readPage(from, from + STORAGE_LOOKUP_PAGE_SIZE - 1);
    if (error) return { error };
    const page = data ?? [];
    rows.push(...page);
    if (page.length < STORAGE_LOOKUP_PAGE_SIZE) return { rows };
  }
}

/**
 * Deleting a LINE account cascades away its Tickets (see 20261007100000_line_user_delete_cascade.sql),
 * but the database can only drop the attachment/signature *rows* — the objects stay in the buckets.
 * Paths are read before the delete, because afterwards there is nothing left to read them from, which
 * is also why a failed lookup is returned rather than swallowed: an empty list is indistinguishable
 * from "no tickets" and would orphan every object without even logging which ones.
 */
async function collectLineUserStoragePaths(
  admin: ReturnType<typeof createAdminClient>,
  lineUserId: string,
): Promise<{ attachments: string[]; signatures: string[] } | { error: PostgrestError }> {
  const ticketResult = await readAllPages<LineTicketPathRow>((from, to) => admin
    .from('tickets')
    .select('id, signature_storage_path, requester_signature_storage_path')
    .eq('requester_line_user_id', lineUserId)
    .order('id')
    .range(from, to));
  if ('error' in ticketResult) return ticketResult;

  const tickets = ticketResult.rows;
  if (tickets.length === 0) return { attachments: [], signatures: [] };

  const attachments: string[] = [];
  for (let index = 0; index < tickets.length; index += STORAGE_LOOKUP_ID_BATCH) {
    const batch = tickets.slice(index, index + STORAGE_LOOKUP_ID_BATCH).map((ticket) => String(ticket.id));
    const attachmentResult = await readAllPages<{ storage_path: string }>((from, to) => admin
      .from('file_attachments')
      .select('storage_path')
      .eq('target_table', 'tickets')
      .in('target_id', batch)
      .order('id')
      .range(from, to));
    if ('error' in attachmentResult) return attachmentResult;
    attachments.push(...attachmentResult.rows.map((row) => String(row.storage_path)).filter(Boolean));
  }

  return {
    attachments,
    signatures: tickets
      .flatMap((ticket) => [ticket.signature_storage_path, ticket.requester_signature_storage_path])
      .filter((path): path is string => typeof path === 'string' && path.length > 0),
  };
}

/**
 * Runs after the delete has already committed, so a storage failure must not fail the request —
 * the rows are gone either way. It is logged with the request id so an orphaned object can be found.
 */
async function removeStoragePaths(
  admin: ReturnType<typeof createAdminClient>,
  bucket: string,
  paths: readonly string[],
  requestId: string,
): Promise<void> {
  const unique = [...new Set(paths)];
  if (unique.length === 0) return;
  const { error } = await admin.storage.from(bucket).remove(unique);
  if (error) {
    console.error(JSON.stringify({ requestId, code: 'RECORD_DELETE_STORAGE_ORPHANED', bucket, paths: unique, message: error.message }));
  }
}

export const recordDeletionsRoute = new Hono<AppEnv>();
recordDeletionsRoute.use('*', requireAuth);

recordDeletionsRoute.delete('/:resource/:id', async (c) => {
  const requestId = c.get('requestId');
  const resourceName = c.req.param('resource');
  const resource = getDeletionResource(resourceName);
  const parsedId = idSchema.safeParse(c.req.param('id'));

  if (!resource || !parsedId.success) {
    return c.json(fail(requestId, 'DELETE_TARGET_INVALID', 'ไม่พบประเภทรายการที่อนุญาตให้ลบ'), 404);
  }

  if (!(await hasPermission(c, resource.permission))) {
    await writeAuditLog(c.env, {
      actorId: c.get('userId'),
      actorEmail: c.get('userEmail'),
      action: 'ACCESS_DENIED',
      module: resource.module,
      targetTable: resource.table,
      targetId: parsedId.data,
      result: 'denied',
      detail: { permissionKeys: [resource.permission], path: c.req.path },
      requestId,
    });
    return c.json(fail(requestId, 'PERMISSION_DENIED', 'ท่านไม่มีสิทธิ์ดำเนินการนี้'), 403);
  }

  let rawBody: unknown;
  try {
    rawBody = await c.req.json();
  } catch {
    rawBody = null;
  }
  const parsedBody = deletionReasonSchema.safeParse(rawBody);
  if (!parsedBody.success) {
    return c.json(fail(requestId, 'RECORD_DELETION_REASON_INVALID', 'กรุณาระบุเหตุผลอย่างน้อย 3 ตัวอักษร'), 400);
  }

  const admin = createAdminClient(c.env);
  let orphanedStorage: { attachments: string[]; signatures: string[] } | null = null;
  if (resourceName === 'line-links') {
    const collected = await collectLineUserStoragePaths(admin, parsedId.data);
    // Stop before the mutation: once the rows are gone the paths cannot be recovered.
    if ('error' in collected) {
      return dbFailJson(
        c,
        'RECORD_DELETE_STORAGE_LOOKUP_FAILED',
        collected.error,
        'ยังลบไม่ได้ เพราะอ่านรายการไฟล์แนบของบัญชีนี้ไม่สำเร็จ กรุณาลองใหม่อีกครั้ง',
      );
    }
    orphanedStorage = collected;
  }
  const { data, error: mutationError } = await admin.rpc('mutate_record_deletion', {
    resource_input: resourceName,
    record_id_input: parsedId.data,
    actor_id_input: c.get('userId'),
    actor_email_input: c.get('userEmail'),
    reason_input: parsedBody.data.reason,
    request_id_input: requestId,
  });

  if (mutationError) {
    if (mutationError.message.includes('DELETE_TARGET_NOT_FOUND')) {
      return c.json(fail(requestId, 'DELETE_TARGET_NOT_FOUND', 'ไม่พบรายการที่ต้องการลบ'), 404);
    }
    if (mutationError.message.includes('PROTECTED_RECORD')) {
      return c.json(fail(requestId, 'PROTECTED_RECORD', 'รายการมาตรฐานของระบบไม่สามารถลบได้'), 409);
    }
    if (mutationError.message.includes('DELETE_TARGET_ALREADY_ARCHIVED')) {
      return c.json(fail(requestId, 'DELETE_TARGET_ALREADY_ARCHIVED', 'รายการนี้ถูกเก็บถาวรไปแล้ว'), 409);
    }
    // 23514 used to fall through to the generic retry message, which told an admin nothing —
    // a check constraint failure never succeeds on retry, it needs the blocking data resolved.
    const dbMessage = mutationError.code === '23503'
      ? 'ยังลบรายการนี้ไม่ได้ เพราะมีข้อมูลอื่นอ้างอิงอยู่ กรุณาลบหรือย้ายข้อมูลที่เกี่ยวข้องก่อน'
      : mutationError.code === '23514'
        ? 'ยังลบรายการนี้ไม่ได้ เพราะจะทำให้ข้อมูลที่เกี่ยวข้องผิดเงื่อนไขของระบบ กรุณาแจ้งผู้ดูแลระบบพร้อมรหัสคำขอนี้'
        : 'ลบรายการไม่สำเร็จ กรุณาลองใหม่อีกครั้ง';
    return dbFailJson(c, 'RECORD_DELETE_FAILED', mutationError, dbMessage);
  }

  if (orphanedStorage) {
    await removeStoragePaths(admin, ATTACHMENTS_BUCKET, orphanedStorage.attachments, requestId);
    await removeStoragePaths(admin, TICKET_SIGNATURE_BUCKET, orphanedStorage.signatures, requestId);
  }

  return c.json(ok(requestId, data));
});
