import { Hono } from 'hono';
import { z } from 'zod';
import { createAdminClient } from '../lib/supabase';
import { requireAuth } from '../middleware/auth';
import { hasPermission } from '../middleware/permission';
import { sanitizeAuditData, writeAuditLog } from '../services/auditService';
import type { AppEnv } from '../types';
import { dbFailJson } from '../utils/dbError';
import { fail, ok } from '../utils/response';

type DeleteMode = 'hard' | 'soft';

interface DeletionResource {
  table: string;
  permission: string;
  module: string;
  mode?: DeleteMode;
  protectedFlag?: string;
}

/**
 * Explicit allowlist for row deletion. The client can only select one of these logical names;
 * it can never submit a database table or permission key directly.
 *
 * Immutable ledgers (audit/login logs, movements, histories, exports and notifications) are
 * deliberately absent. They are evidence generated by the system, not user-managed records.
 */
const DELETION_RESOURCES = {
  'access-requests': { table: 'access_requests', permission: 'access_request.process', module: 'access-request' },
  'access-registry': { table: 'user_access_registry', permission: 'access_registry.manage', module: 'access-registry' },
  'access-systems': { table: 'access_systems', permission: 'access_system.manage', module: 'access-system' },
  'approval-groups': { table: 'approval_groups', permission: 'approval_group.manage', module: 'approval-group' },
  'asset-categories': { table: 'asset_categories', permission: 'asset_category.manage', module: 'asset-category' },
  assets: { table: 'assets', permission: 'asset.dispose', module: 'asset' },
  'backup-logs': { table: 'backup_logs', permission: 'backup.manage', module: 'backup' },
  'bcp-plans': { table: 'bcp_plans', permission: 'backup.manage', module: 'backup' },
  'cause-codes': { table: 'ticket_cause_codes', permission: 'cause_code.manage', module: 'cause-code' },
  changes: { table: 'change_requests', permission: 'change.approve', module: 'change' },
  'ci-relationships': { table: 'ci_relationships', permission: 'cmdb.manage', module: 'cmdb' },
  'configuration-items': { table: 'configuration_items', permission: 'cmdb.manage', module: 'cmdb' },
  contracts: { table: 'contracts', permission: 'contract.manage', module: 'contract' },
  departments: { table: 'departments', permission: 'department.manage', module: 'department' },
  'employee-assignments': { table: 'employee_assignments', permission: 'employee.manage', module: 'employee-assignment' },
  employees: { table: 'employees', permission: 'employee.manage', module: 'employee' },
  'form-templates': { table: 'form_templates', permission: 'form.manage', module: 'form' },
  incidents: { table: 'incidents', permission: 'incident.manage', module: 'incident' },
  'inventory-items': { table: 'inventory_items', permission: 'inventory.manage', module: 'inventory' },
  'issue-forms': { table: 'issue_forms', permission: 'form.manage', module: 'form' },
  'line-links': { table: 'line_users', permission: 'line.manage', module: 'line' },
  'log-reviews': { table: 'log_reviews', permission: 'monitoring.manage', module: 'monitoring' },
  'logging-systems': { table: 'logging_systems', permission: 'monitoring.manage', module: 'monitoring' },
  'known-errors': { table: 'known_errors', permission: 'problem.manage', module: 'problem' },
  'maintenance-plans': { table: 'maintenance_plans', permission: 'maintenance.manage', module: 'maintenance' },
  positions: { table: 'positions', permission: 'position.manage', module: 'position' },
  problems: { table: 'problems', permission: 'problem.manage', module: 'problem' },
  'recovery-tests': { table: 'recovery_tests', permission: 'backup.manage', module: 'backup' },
  roles: { table: 'roles', permission: 'role.manage', module: 'role', protectedFlag: 'is_system' },
  'service-catalog': { table: 'service_catalog', permission: 'service_catalog.manage', module: 'service-catalog' },
  'service-requests': { table: 'service_requests', permission: 'service_request.close', module: 'service-request' },
  'software-licenses': { table: 'software_licenses', permission: 'license.manage', module: 'license' },
  'ticket-categories': { table: 'ticket_categories', permission: 'ticket_category.manage', module: 'ticket-category', protectedFlag: 'is_security_default' },
  tickets: { table: 'tickets', permission: 'ticket.close', module: 'ticket', mode: 'soft' },
  vendors: { table: 'vendors', permission: 'vendor.manage', module: 'vendor' },
  vulnerabilities: { table: 'vulnerability_findings', permission: 'vulnerability.manage', module: 'vulnerability' },
  'workflow-definitions': { table: 'workflow_definitions', permission: 'workflow.manage', module: 'workflow' },
  'workflow-instances': { table: 'workflow_instances', permission: 'workflow.manage', module: 'workflow' },
} as const satisfies Record<string, DeletionResource>;

export type DeletionResourceName = keyof typeof DELETION_RESOURCES;

export function getDeletionResource(name: string): DeletionResource | undefined {
  return Object.prototype.hasOwnProperty.call(DELETION_RESOURCES, name)
    ? DELETION_RESOURCES[name as DeletionResourceName]
    : undefined;
}

export const deletionResourceNames = Object.freeze(Object.keys(DELETION_RESOURCES));

const idSchema = z.string().uuid();

export const recordDeletionsRoute = new Hono<AppEnv>();
recordDeletionsRoute.use('*', requireAuth);

recordDeletionsRoute.delete('/:resource/:id', async (c) => {
  const requestId = c.get('requestId');
  const resourceName = c.req.param('resource');
  const resource = getDeletionResource(resourceName);
  const parsedId = idSchema.safeParse(c.req.param('id'));

  if (!resource || !parsedId.success) {
    return c.json(fail(requestId, 'DELETE_TARGET_INVALID', 'ไม่พบประเภทรายการที่อนุญาตให้ลบ'), 404);
  }

  if (!(await hasPermission(c, resource.permission))) {
    await writeAuditLog(c.env, {
      actorId: c.get('userId'),
      actorEmail: c.get('userEmail'),
      action: 'ACCESS_DENIED',
      module: resource.module,
      targetTable: resource.table,
      targetId: parsedId.data,
      result: 'denied',
      detail: { permissionKeys: [resource.permission], path: c.req.path },
      requestId,
    });
    return c.json(fail(requestId, 'PERMISSION_DENIED', 'ท่านไม่มีสิทธิ์ดำเนินการนี้'), 403);
  }

  const admin = createAdminClient(c.env);
  const { data: existing, error: loadError } = await admin
    .from(resource.table)
    .select('*')
    .eq('id', parsedId.data)
    .maybeSingle();

  if (loadError) return dbFailJson(c, 'DELETE_TARGET_LOAD_FAILED', loadError, 'ตรวจสอบรายการก่อนลบไม่สำเร็จ');
  if (!existing) return c.json(fail(requestId, 'DELETE_TARGET_NOT_FOUND', 'ไม่พบรายการที่ต้องการลบ'), 404);
  if (resource.protectedFlag && existing[resource.protectedFlag] === true) {
    return c.json(fail(requestId, 'PROTECTED_RECORD', 'รายการมาตรฐานของระบบไม่สามารถลบได้'), 409);
  }

  const mode = resource.mode ?? 'hard';
  const mutation = mode === 'soft'
    ? admin.from(resource.table).update({ deleted_at: new Date().toISOString(), updated_by: c.get('userId') }).eq('id', parsedId.data).select('id').maybeSingle()
    : admin.from(resource.table).delete().eq('id', parsedId.data).select('id').maybeSingle();
  const { data: deleted, error: deleteError } = await mutation;

  if (deleteError) {
    return dbFailJson(
      c,
      'RECORD_DELETE_FAILED',
      deleteError,
      deleteError.code === '23503'
        ? 'ยังลบรายการนี้ไม่ได้ เพราะมีข้อมูลอื่นอ้างอิงอยู่ กรุณาลบหรือย้ายข้อมูลที่เกี่ยวข้องก่อน'
        : 'ลบรายการไม่สำเร็จ กรุณาลองใหม่อีกครั้ง',
    );
  }
  if (!deleted) return c.json(fail(requestId, 'DELETE_TARGET_NOT_FOUND', 'ไม่พบรายการที่ต้องการลบ'), 404);

  await writeAuditLog(c.env, {
    actorId: c.get('userId'),
    actorEmail: c.get('userEmail'),
    action: mode === 'soft' ? 'SOFT_DELETE' : 'DELETE',
    module: resource.module,
    targetTable: resource.table,
    targetId: parsedId.data,
    before: sanitizeAuditData(existing),
    detail: { resource: resourceName, mode },
    requestId,
  });

  return c.json(ok(requestId, { id: parsedId.data, resource: resourceName, mode }));
});
