/** Problem/Known Error, Vulnerability remediation และ Audit Management */
const ASSURANCE_STATUSES = ['เปิด', 'กำลังวิเคราะห์', 'กำลังแก้ไข', 'รอตรวจยืนยัน', 'ปิด'];

function getProblemModuleData() {
  try { const u=requireModule('problem',false); return ok({canEdit:canEditModule(u.role,'problem'),
    problems:readSheetObjectsEnsured_(SHEETS.PROBLEM).map(assuranceProblemDto_),
    knownErrors:readSheetObjectsEnsured_(SHEETS.KNOWN_ERROR).map(assuranceKnownErrorDto_), statuses:ASSURANCE_STATUSES});
  } catch(e){return fail(e.message,'PROBLEM_LOAD_FAILED');}
}
function saveProblemRecord(f) {
  try { const u=requireModule('problem',true); f=f||{}; requireFields({title:f.title},['title']);
    const p={Title:sanitizeText(f.title,200),Category:sanitizeText(f.category,100),AffectedSystem:sanitizeText(f.affectedSystem,200),
      RelatedIncidentIDs:sanitizeText(f.relatedIncidentIds,500),RelatedTicketIDs:sanitizeText(f.relatedTicketIds,500),Impact:sanitizeText(f.impact,1000),
      RootCause:sanitizeText(f.rootCause,1500),Workaround:sanitizeText(f.workaround,1500),PermanentFix:sanitizeText(f.permanentFix,1500),
      Owner:sanitizeText(f.owner,150)||u.email,Priority:sanitizeText(f.priority,30)||'ปานกลาง',Status:sanitizeText(f.status,50)||'เปิด',
      ReviewDate:parseDate(f.reviewDate),EvidenceLink:assuranceUrl_(f.evidenceLink),Notes:sanitizeText(f.notes,1000)};
    if(p.Status==='ปิด') p.ClosedAt=new Date(); const id=sanitizeText(f.id,80);
    if(id){const r=findRow_(SHEETS.PROBLEM,'ProblemID',id);if(!r)throw new Error('ไม่พบ Problem');updateRow_(SHEETS.PROBLEM,r._row,p,u.email);writeAudit_(u,'UPDATE_PROBLEM','problem',SHEETS.PROBLEM,id,p.Title,'success');return ok({id:id},'อัปเดต Problem แล้ว');}
    p.ProblemID=generateId('PRB');appendRow_(SHEETS.PROBLEM,p,u.email);writeAudit_(u,'CREATE_PROBLEM','problem',SHEETS.PROBLEM,p.ProblemID,p.Title,'success');return ok({id:p.ProblemID},'สร้าง Problem แล้ว');
  } catch(e){return fail(e.message,'PROBLEM_SAVE_FAILED');}
}
function saveKnownErrorRecord(f) {
  try { const u=requireModule('problem',true);f=f||{};requireFields({problemId:f.problemId,title:f.title,workaround:f.workaround},['problemId','title','workaround']);
    if(!findRow_(SHEETS.PROBLEM,'ProblemID',sanitizeText(f.problemId,80)))throw new Error('ไม่พบ Problem ที่อ้างอิง');
    const p={ProblemID:sanitizeText(f.problemId,80),Title:sanitizeText(f.title,200),Symptoms:sanitizeText(f.symptoms,1500),RootCause:sanitizeText(f.rootCause,1500),
      Workaround:sanitizeText(f.workaround,1500),AffectedVersions:sanitizeText(f.affectedVersions,500),FixedVersion:sanitizeText(f.fixedVersion,200),
      KnowledgeArticleID:sanitizeText(f.knowledgeArticleId,80),Status:sanitizeText(f.status,50)||'เผยแพร่',ReviewDate:parseDate(f.reviewDate),Notes:sanitizeText(f.notes,1000)};
    const id=sanitizeText(f.id,80);if(id){const r=findRow_(SHEETS.KNOWN_ERROR,'KnownErrorID',id);if(!r)throw new Error('ไม่พบ Known Error');updateRow_(SHEETS.KNOWN_ERROR,r._row,p,u.email);writeAudit_(u,'UPDATE_KNOWN_ERROR','problem',SHEETS.KNOWN_ERROR,id,p.Title,'success');return ok({id:id},'อัปเดต Known Error แล้ว');}
    p.KnownErrorID=generateId('KEDB');appendRow_(SHEETS.KNOWN_ERROR,p,u.email);writeAudit_(u,'CREATE_KNOWN_ERROR','problem',SHEETS.KNOWN_ERROR,p.KnownErrorID,p.Title,'success');return ok({id:p.KnownErrorID},'สร้าง Known Error แล้ว');
  } catch(e){return fail(e.message,'KNOWN_ERROR_SAVE_FAILED');}
}
function getVulnerabilityModuleData(){try{const u=requireModule('vulnerability',false);return ok({canEdit:canEditModule(u.role,'vulnerability'),statuses:ASSURANCE_STATUSES,findings:readSheetObjectsEnsured_(SHEETS.VULNERABILITY).map(assuranceVulnDto_)});}catch(e){return fail(e.message,'VULNERABILITY_LOAD_FAILED');}}
function saveVulnerabilityFinding(f){try{const u=requireModule('vulnerability',true);f=f||{};requireFields({title:f.title,severity:f.severity},['title','severity']);
  const cvss=f.cvss===''||f.cvss===undefined?'':Number(f.cvss);if(cvss!==''&&(isNaN(cvss)||cvss<0||cvss>10))throw new Error('CVSS ต้องอยู่ระหว่าง 0-10');
  const p={Title:sanitizeText(f.title,200),AssetID:sanitizeText(f.assetId,80),AffectedSystem:sanitizeText(f.affectedSystem,200),Source:sanitizeText(f.source,150),CVE:sanitizeText(f.cve,100),CVSS:cvss,Severity:sanitizeText(f.severity,30),Description:sanitizeText(f.description,1500),DetectedAt:parseDate(f.detectedAt)||new Date(),Owner:sanitizeText(f.owner,150)||u.email,RemediationPlan:sanitizeText(f.remediationPlan,1500),DueDate:parseDate(f.dueDate),Status:sanitizeText(f.status,50)||'เปิด',ExceptionReason:sanitizeText(f.exceptionReason,1000),ExceptionExpiry:parseDate(f.exceptionExpiry),EvidenceLink:assuranceUrl_(f.evidenceLink),Notes:sanitizeText(f.notes,1000)};
  const id=sanitizeText(f.id,80);if(id){const r=findRow_(SHEETS.VULNERABILITY,'VulnerabilityID',id);if(!r)throw new Error('ไม่พบช่องโหว่');if(!f.detectedAt)p.DetectedAt=r.DetectedAt;if(!f.dueDate)p.DueDate=r.DueDate;updateRow_(SHEETS.VULNERABILITY,r._row,p,u.email);writeAudit_(u,'UPDATE_VULNERABILITY','vulnerability',SHEETS.VULNERABILITY,id,p.Title,'success');return ok({id:id},'อัปเดตช่องโหว่แล้ว');}
  p.VulnerabilityID=generateId('VUL');appendRow_(SHEETS.VULNERABILITY,p,u.email);writeAudit_(u,'CREATE_VULNERABILITY','vulnerability',SHEETS.VULNERABILITY,p.VulnerabilityID,p.Title,'success');return ok({id:p.VulnerabilityID},'บันทึกช่องโหว่แล้ว');}catch(e){return fail(e.message,'VULNERABILITY_SAVE_FAILED');}}
function updateVulnerabilityStatus(id,status,evidence){try{const u=requireModule('vulnerability',true);if(!isInList(status,ASSURANCE_STATUSES))throw new Error('สถานะไม่ถูกต้อง');const r=findRow_(SHEETS.VULNERABILITY,'VulnerabilityID',id);if(!r)throw new Error('ไม่พบช่องโหว่');const p={Status:status};if(evidence)p.EvidenceLink=assuranceUrl_(evidence);if(status==='ปิด'){if(String(r.Owner).toLowerCase()===u.email)throw new Error('ผู้รับผิดชอบการแก้ไขห้ามเป็นผู้ตรวจยืนยันปิดรายการเดียวกัน');p.VerifiedAt=new Date();p.VerifiedBy=u.email;}updateRow_(SHEETS.VULNERABILITY,r._row,p,u.email);writeAudit_(u,'VERIFY_VULNERABILITY','vulnerability',SHEETS.VULNERABILITY,id,status,'success');return ok({id:id},'อัปเดตสถานะแล้ว');}catch(e){return fail(e.message,'VULNERABILITY_STATUS_FAILED');}}

function getAuditModuleData(){try{const u=requireModule('audit',false);return ok({canEdit:canEditModule(u.role,'audit'),statuses:ASSURANCE_STATUSES,audits:readSheetObjectsEnsured_(SHEETS.AUDIT_ENGAGEMENT).map(assuranceAuditDto_),findings:readSheetObjectsEnsured_(SHEETS.AUDIT_FINDING).map(assuranceAuditFindingDto_)});}catch(e){return fail(e.message,'AUDIT_LOAD_FAILED');}}
function saveAuditEngagement(f){try{const u=requireModule('audit',true);f=f||{};requireFields({title:f.title,scope:f.scope},['title','scope']);const p={Title:sanitizeText(f.title,200),AuditType:sanitizeText(f.auditType,80),Scope:sanitizeText(f.scope,1500),Criteria:sanitizeText(f.criteria,1000),LeadAuditor:sanitizeText(f.leadAuditor,150)||u.email,Auditee:sanitizeText(f.auditee,250),PlannedStart:parseDate(f.plannedStart),PlannedEnd:parseDate(f.plannedEnd),Status:sanitizeText(f.status,50)||'เปิด',Conclusion:sanitizeText(f.conclusion,1500),ReportLink:assuranceUrl_(f.reportLink),Notes:sanitizeText(f.notes,1000)};if(p.Status==='ปิด')p.ClosedAt=new Date();const id=sanitizeText(f.id,80);if(id){const r=findRow_(SHEETS.AUDIT_ENGAGEMENT,'AuditID',id);if(!r)throw new Error('ไม่พบงานตรวจ');updateRow_(SHEETS.AUDIT_ENGAGEMENT,r._row,p,u.email);writeAudit_(u,'UPDATE_AUDIT','audit',SHEETS.AUDIT_ENGAGEMENT,id,p.Title,'success');return ok({id:id},'อัปเดตงานตรวจแล้ว');}p.AuditID=generateId('AUD');appendRow_(SHEETS.AUDIT_ENGAGEMENT,p,u.email);writeAudit_(u,'CREATE_AUDIT','audit',SHEETS.AUDIT_ENGAGEMENT,p.AuditID,p.Title,'success');return ok({id:p.AuditID},'สร้างงานตรวจแล้ว');}catch(e){return fail(e.message,'AUDIT_SAVE_FAILED');}}
function saveAuditFinding(f){try{const u=requireModule('audit',true);f=f||{};requireFields({auditId:f.auditId,title:f.title},['auditId','title']);if(!findRow_(SHEETS.AUDIT_ENGAGEMENT,'AuditID',sanitizeText(f.auditId,80)))throw new Error('ไม่พบงานตรวจที่อ้างอิง');const p={AuditID:sanitizeText(f.auditId,80),Title:sanitizeText(f.title,200),FindingType:sanitizeText(f.findingType,80),Requirement:sanitizeText(f.requirement,1000),Evidence:sanitizeText(f.evidence,1500),RootCause:sanitizeText(f.rootCause,1500),ActionPlan:sanitizeText(f.actionPlan,1500),Owner:sanitizeText(f.owner,150),DueDate:parseDate(f.dueDate),Status:sanitizeText(f.status,50)||'เปิด',EvidenceLink:assuranceUrl_(f.evidenceLink),Notes:sanitizeText(f.notes,1000)};const id=sanitizeText(f.id,80);if(id){const r=findRow_(SHEETS.AUDIT_FINDING,'FindingID',id);if(!r)throw new Error('ไม่พบข้อตรวจพบ');updateRow_(SHEETS.AUDIT_FINDING,r._row,p,u.email);writeAudit_(u,'UPDATE_AUDIT_FINDING','audit',SHEETS.AUDIT_FINDING,id,p.Title,'success');return ok({id:id},'อัปเดตข้อตรวจพบแล้ว');}p.FindingID=generateId('FND');appendRow_(SHEETS.AUDIT_FINDING,p,u.email);writeAudit_(u,'CREATE_AUDIT_FINDING','audit',SHEETS.AUDIT_FINDING,p.FindingID,p.Title,'success');return ok({id:p.FindingID},'สร้างข้อตรวจพบแล้ว');}catch(e){return fail(e.message,'AUDIT_FINDING_SAVE_FAILED');}}
function updateAuditFindingStatus(id,status,evidence){try{const u=requireModule('audit',true);if(!isInList(status,ASSURANCE_STATUSES))throw new Error('สถานะไม่ถูกต้อง');const r=findRow_(SHEETS.AUDIT_FINDING,'FindingID',id);if(!r)throw new Error('ไม่พบข้อตรวจพบ');const p={Status:status};if(evidence)p.EvidenceLink=assuranceUrl_(evidence);if(status==='ปิด'){if(String(r.Owner).toLowerCase()===u.email)throw new Error('เจ้าของแผนแก้ไขห้ามตรวจยืนยันปิดข้อตรวจพบของตนเอง');p.CompletedAt=r.CompletedAt||new Date();p.VerifiedAt=new Date();p.VerifiedBy=u.email;}updateRow_(SHEETS.AUDIT_FINDING,r._row,p,u.email);writeAudit_(u,'VERIFY_AUDIT_FINDING','audit',SHEETS.AUDIT_FINDING,id,status,'success');return ok({id:id},'อัปเดตข้อตรวจพบแล้ว');}catch(e){return fail(e.message,'AUDIT_FINDING_STATUS_FAILED');}}

function assuranceProblemDto_(r){return{id:r.ProblemID,title:r.Title,category:r.Category,system:r.AffectedSystem,incidents:r.RelatedIncidentIDs,tickets:r.RelatedTicketIDs,impact:r.Impact,rootCause:r.RootCause,workaround:r.Workaround,fix:r.PermanentFix,owner:r.Owner,priority:r.Priority,status:r.Status,reviewDate:fmtDate(r.ReviewDate),notes:r.Notes};}
function assuranceKnownErrorDto_(r){return{id:r.KnownErrorID,problemId:r.ProblemID,title:r.Title,symptoms:r.Symptoms,rootCause:r.RootCause,workaround:r.Workaround,versions:r.AffectedVersions,fixedVersion:r.FixedVersion,kb:r.KnowledgeArticleID,status:r.Status,reviewDate:fmtDate(r.ReviewDate)};}
function assuranceVulnDto_(r){return{id:r.VulnerabilityID,title:r.Title,assetId:r.AssetID,system:r.AffectedSystem,source:r.Source,cve:r.CVE,cvss:r.CVSS,severity:r.Severity,description:r.Description,detectedAt:fmtDate(r.DetectedAt),owner:r.Owner,plan:r.RemediationPlan,dueDate:fmtDate(r.DueDate),dueDateInput:assuranceIsoDate_(r.DueDate),dueDays:daysUntil(r.DueDate),status:r.Status,exception:r.ExceptionReason,verifiedBy:r.VerifiedBy,evidence:r.EvidenceLink};}
function assuranceAuditDto_(r){return{id:r.AuditID,title:r.Title,type:r.AuditType,scope:r.Scope,criteria:r.Criteria,lead:r.LeadAuditor,auditee:r.Auditee,start:fmtDate(r.PlannedStart),end:fmtDate(r.PlannedEnd),status:r.Status,conclusion:r.Conclusion,report:r.ReportLink};}
function assuranceAuditFindingDto_(r){return{id:r.FindingID,auditId:r.AuditID,title:r.Title,type:r.FindingType,requirement:r.Requirement,evidenceText:r.Evidence,rootCause:r.RootCause,plan:r.ActionPlan,owner:r.Owner,dueDate:fmtDate(r.DueDate),dueDays:daysUntil(r.DueDate),status:r.Status,verifiedBy:r.VerifiedBy,evidence:r.EvidenceLink};}
function assuranceUrl_(v){const s=sanitizeText(v,500);if(!s)return'';if(!/^https:\/\//i.test(s))throw new Error('ลิงก์หลักฐานต้องเป็น HTTPS');return s;}
function assuranceIsoDate_(v){if(!v)return'';const d=v instanceof Date?v:new Date(v);return isNaN(d)?'':Utilities.formatDate(d,'Asia/Bangkok','yyyy-MM-dd');}
