import type { GovernanceDomain, GovernanceRecord } from '../../types/governance';

export type GovernanceField = {
  key: string; label: string; type?: 'text' | 'textarea' | 'number' | 'date' | 'url' | 'checkbox' | 'select';
  required?: boolean; options?: string[]; min?: number; max?: number; placeholder?: string;
};

export type GovernanceForm = { entity: string; label: string; fields: GovernanceField[] };
export type GovernanceDomainConfig = {
  domain: GovernanceDomain; label: string; shortLabel: string; description: string;
  viewPermission: string; managePermission?: string; forms: GovernanceForm[];
};

const status = (options: string[]): GovernanceField => ({ key: 'status', label: 'สถานะ', type: 'select', options, required: true });
const notes: GovernanceField = { key: 'notes', label: 'หมายเหตุ', type: 'textarea' };

export const GOVERNANCE_DOMAINS: GovernanceDomainConfig[] = [
  { domain: 'data-classification', label: 'Data Classification', shortLabel: 'ข้อมูล', description: 'จัดชั้นข้อมูล ระยะเก็บรักษา และ workflow อนุมัติทำลายข้อมูล', viewPermission: 'data_class.view', managePermission: 'data_class.manage', forms: [
    { entity: 'data-assets', label: 'เพิ่มชุดข้อมูล', fields: [
      { key: 'dataName', label: 'ชื่อชุดข้อมูล', required: true }, { key: 'systemName', label: 'ระบบงาน', required: true },
      { key: 'classification', label: 'ชั้นความลับ', type: 'select', options: ['ลับมาก', 'ลับ', 'ไม่ลับ'], required: true },
      { key: 'dataOwner', label: 'เจ้าของข้อมูล', required: true }, { key: 'custodian', label: 'ผู้ดูแลข้อมูล' },
      { key: 'storageMethod', label: 'วิธี/ตำแหน่งจัดเก็บ' }, { key: 'retentionDays', label: 'เก็บรักษา (วัน)', type: 'number', min: 1, max: 36500 },
      { key: 'containsPersonalData', label: 'มีข้อมูลส่วนบุคคล', type: 'checkbox' }, status(['ใช้งาน', 'ระงับ', 'ยกเลิก']), notes,
    ] },
    { entity: 'destruction-requests', label: 'ขอทำลายข้อมูล', fields: [{ key: 'dataAssetId', label: 'UUID ชุดข้อมูล', required: true }, { key: 'reason', label: 'เหตุผล', type: 'textarea', required: true }] },
  ] },
  { domain: 'compliance', label: 'Legal Compliance', shortLabel: 'กฎหมาย', description: 'ทะเบียนกฎหมาย ข้อกำหนด Assessment และแผนแก้ไข CAPA', viewPermission: 'compliance.view', managePermission: 'compliance.manage', forms: [
    { entity: 'laws', label: 'เพิ่มกฎหมาย/กรอบ', fields: [{ key: 'lawName', label: 'ชื่อกฎหมาย/กรอบ', required: true }, { key: 'shortName', label: 'ชื่อย่อ' }, { key: 'authority', label: 'หน่วยงานผู้ออก' }, { key: 'version', label: 'ฉบับ/เวอร์ชัน' }, { key: 'effectiveDate', label: 'วันที่มีผล', type: 'date' }, { key: 'applicabilityStatus', label: 'การใช้บังคับ', type: 'select', options: ['ใช้บังคับ', 'ใช้เป็นกรอบ', 'ต้องยืนยัน', 'ไม่เกี่ยวข้อง'], required: true }, { key: 'owner', label: 'เจ้าของข้อกำหนด' }, { key: 'sourceUrl', label: 'URL แหล่งทางการ', type: 'url' }, status(['ใช้งาน', 'รอทบทวน', 'ยกเลิก']), notes] },
    { entity: 'obligations', label: 'เพิ่มข้อกำหนด', fields: [{ key: 'lawId', label: 'UUID กฎหมาย', required: true }, { key: 'clause', label: 'มาตรา/ข้อ' }, { key: 'requirement', label: 'ข้อกำหนด', type: 'textarea', required: true }, { key: 'controlDomain', label: 'Control domain' }, { key: 'controlOwner', label: 'ผู้รับผิดชอบ' }, { key: 'frequency', label: 'ความถี่' }, { key: 'dueDate', label: 'กำหนดทบทวน', type: 'date' }, status(['เปิด', 'พักใช้', 'ปิด']), notes] },
    { entity: 'assessments', label: 'บันทึก Assessment', fields: [{ key: 'obligationId', label: 'UUID ข้อกำหนด', required: true }, { key: 'assessmentDate', label: 'วันที่ประเมิน', type: 'date', required: true }, { key: 'result', label: 'ผล', type: 'select', options: ['สอดคล้อง', 'สอดคล้องบางส่วน', 'ไม่สอดคล้อง', 'ไม่เกี่ยวข้อง'], required: true }, { key: 'controlDescription', label: 'มาตรการที่มี', type: 'textarea' }, { key: 'evidenceUrl', label: 'หลักฐาน HTTPS', type: 'url' }, { key: 'gapDescription', label: 'ช่องว่าง', type: 'textarea' }, { key: 'nextReviewDue', label: 'ทบทวนครั้งถัดไป', type: 'date' }, notes] },
    { entity: 'corrective-actions', label: 'เปิด CAPA', fields: [{ key: 'obligationId', label: 'UUID ข้อกำหนด', required: true }, { key: 'assessmentId', label: 'UUID Assessment' }, { key: 'title', label: 'หัวข้อ', required: true }, { key: 'rootCause', label: 'Root cause', type: 'textarea' }, { key: 'actionPlan', label: 'แผนแก้ไข', type: 'textarea', required: true }, { key: 'owner', label: 'เจ้าของงาน', required: true }, { key: 'priority', label: 'Priority', type: 'select', options: ['วิกฤต', 'สูง', 'ปานกลาง', 'ต่ำ'] }, { key: 'dueDate', label: 'Due date', type: 'date' }, status(['เปิด', 'กำลังดำเนินการ', 'รอตรวจสอบ', 'เสร็จสิ้น', 'ยกเลิก']), notes] },
  ] },
  { domain: 'privacy', label: 'Privacy / PDPA', shortLabel: 'PDPA', description: 'RoPA หลักฐานความยินยอม และคำขอใช้สิทธิของเจ้าของข้อมูล', viewPermission: 'privacy.view', managePermission: 'privacy.manage', forms: [
    { entity: 'ropa', label: 'เพิ่ม RoPA', fields: [{ key: 'processName', label: 'กิจกรรมประมวลผล', required: true }, { key: 'department', label: 'หน่วยงาน', required: true }, { key: 'dataOwner', label: 'Data owner' }, { key: 'purpose', label: 'วัตถุประสงค์', type: 'textarea', required: true }, { key: 'lawfulBasis', label: 'ฐานกฎหมาย', type: 'select', options: ['ความยินยอม', 'สัญญา', 'หน้าที่ตามกฎหมาย', 'ประโยชน์สำคัญต่อชีวิต', 'ภารกิจเพื่อประโยชน์สาธารณะ', 'ประโยชน์โดยชอบด้วยกฎหมาย'], required: true }, { key: 'personalData', label: 'ข้อมูลส่วนบุคคล', type: 'textarea' }, { key: 'sensitiveData', label: 'ข้อมูลอ่อนไหว', type: 'textarea' }, { key: 'crossBorderTransfer', label: 'โอนข้ามประเทศ', type: 'checkbox' }, { key: 'dpiaRequired', label: 'ต้องทำ DPIA', type: 'checkbox' }, { key: 'reviewDate', label: 'วันทบทวน', type: 'date' }, status(['ร่าง', 'ใช้งาน', 'รอทบทวน', 'ยกเลิก']), notes] },
    { entity: 'consents', label: 'บันทึกความยินยอม', fields: [{ key: 'dataSubjectRef', label: 'รหัสเจ้าของข้อมูล', required: true }, { key: 'purpose', label: 'วัตถุประสงค์', required: true }, { key: 'noticeVersion', label: 'Privacy Notice version', required: true }, { key: 'channel', label: 'ช่องทาง', required: true }, { key: 'grantedAt', label: 'วันที่ให้ความยินยอม', type: 'date', required: true }, { key: 'evidenceUrl', label: 'หลักฐาน HTTPS', type: 'url' }, notes] },
    { entity: 'dsr', label: 'รับคำขอ DSR', fields: [{ key: 'requestType', label: 'ประเภทคำขอ', type: 'select', options: ['ขอเข้าถึงข้อมูล', 'ขอสำเนาข้อมูล', 'ขอแก้ไขข้อมูล', 'ขอลบข้อมูล', 'ขอระงับการใช้', 'ขอคัดค้าน', 'ขอโอนย้ายข้อมูล', 'ถอนความยินยอม'], required: true }, { key: 'dataSubjectRef', label: 'รหัสเจ้าของข้อมูล', required: true }, { key: 'contact', label: 'ช่องทางติดต่อ', required: true }, { key: 'owner', label: 'ผู้รับผิดชอบ' }, status(['รับคำขอ', 'รอยืนยันตัวตน', 'กำลังดำเนินการ', 'รอข้อมูลเพิ่มเติม', 'เสร็จสิ้น', 'ปฏิเสธ']), notes] },
  ] },
  { domain: 'risk', label: 'Risk Register', shortLabel: 'ความเสี่ยง', description: 'ประเมิน Inherent/Residual Risk 5×5 และแผนจัดการตาม ISO 27001', viewPermission: 'risk.view', managePermission: 'risk.manage', forms: [
    { entity: 'risks', label: 'เพิ่มความเสี่ยง', fields: [{ key: 'title', label: 'ชื่อความเสี่ยง', required: true }, { key: 'category', label: 'ประเภท', type: 'select', options: ['บุคลากร', 'กระบวนการ', 'เทคโนโลยี/ระบบ', 'ข้อมูล/สารสนเทศ', 'ผู้ให้บริการภายนอก', 'กฎหมาย/กำกับดูแล', 'กายภาพ/สิ่งแวดล้อม'] }, { key: 'relatedSystem', label: 'ระบบที่เกี่ยวข้อง' }, { key: 'threat', label: 'ภัยคุกคาม', type: 'textarea' }, { key: 'vulnerability', label: 'ช่องโหว่', type: 'textarea' }, { key: 'owner', label: 'Risk owner', required: true }, { key: 'likelihood', label: 'Likelihood (1-5)', type: 'number', min: 1, max: 5, required: true }, { key: 'impact', label: 'Impact (1-5)', type: 'number', min: 1, max: 5, required: true }, { key: 'treatment', label: 'การจัดการ', type: 'select', options: ['ลดความเสี่ยง (Mitigate)', 'ยอมรับความเสี่ยง (Accept)', 'โอนความเสี่ยง (Transfer)', 'หลีกเลี่ยงความเสี่ยง (Avoid)'] }, { key: 'treatmentPlan', label: 'แผนจัดการ', type: 'textarea' }, { key: 'dueDate', label: 'Due date', type: 'date' }, status(['เปิด', 'กำลังจัดการ', 'เฝ้าระวัง', 'ปิด']), notes] },
  ] },
  { domain: 'ai-cloud', label: 'AI / Cloud Register', shortLabel: 'AI/Cloud', description: 'กำกับการใช้เครื่องมือ AI และบริการ Cloud พร้อมข้อจำกัดข้อมูล/Exit plan', viewPermission: 'ai_cloud.view', managePermission: 'ai_cloud.manage', forms: [
    { entity: 'ai-tools', label: 'เพิ่มเครื่องมือ AI', fields: [{ key: 'toolName', label: 'ชื่อเครื่องมือ', required: true }, { key: 'vendor', label: 'ผู้ให้บริการ' }, { key: 'purpose', label: 'วัตถุประสงค์', type: 'textarea' }, { key: 'allowedDataTypes', label: 'ข้อมูลที่อนุญาต' }, { key: 'prohibitedDataTypes', label: 'ข้อมูลต้องห้าม', required: true }, { key: 'owner', label: 'Owner' }, { key: 'approvalRef', label: 'เลขอนุมัติ' }, status(['รออนุมัติ', 'อนุมัติ', 'ระงับ', 'ยกเลิก']), notes] },
    { entity: 'cloud-services', label: 'เพิ่มบริการ Cloud', fields: [{ key: 'serviceName', label: 'ชื่อบริการ', required: true }, { key: 'provider', label: 'Provider', required: true }, { key: 'purpose', label: 'วัตถุประสงค์', type: 'textarea' }, { key: 'allowedDataClass', label: 'ชั้นข้อมูลสูงสุด', type: 'select', options: ['ไม่ลับ', 'ลับ', 'ลับมาก'] }, { key: 'owner', label: 'Owner' }, { key: 'approvalRef', label: 'เลขอนุมัติ' }, { key: 'backupArrangement', label: 'การสำรองข้อมูล', type: 'textarea' }, { key: 'exitPlan', label: 'Exit plan', type: 'textarea', required: true }, { key: 'contractExpiry', label: 'หมดสัญญา', type: 'date' }, status(['รออนุมัติ', 'ใช้งาน', 'ระงับ', 'ยกเลิก']), notes] },
  ] },
  { domain: 'awareness', label: 'Awareness Training', shortLabel: 'อบรม', description: 'แผนอบรม แบบทดสอบ บันทึกผู้เข้า และ e-sign รับทราบนโยบาย', viewPermission: 'awareness.view', managePermission: 'awareness.manage', forms: [
    { entity: 'training-plans', label: 'เพิ่มแผนอบรม', fields: [{ key: 'year', label: 'ปี', type: 'number', required: true }, { key: 'quarter', label: 'ไตรมาส', type: 'select', options: ['Q1', 'Q2', 'Q3', 'Q4'], required: true }, { key: 'topic', label: 'หัวข้อ', required: true }, { key: 'targetGroup', label: 'กลุ่มเป้าหมาย' }, { key: 'plannedDate', label: 'วันที่วางแผน', type: 'date' }, { key: 'responsible', label: 'ผู้รับผิดชอบ' }, { key: 'passingScore', label: 'เกณฑ์ผ่าน (%)', type: 'number', min: 0, max: 100 }, status(['วางแผน', 'เปิดลงทะเบียน', 'กำลังดำเนินการ', 'เสร็จสิ้น', 'ยกเลิก']), notes] },
    { entity: 'acknowledgements', label: 'ลงชื่อรับทราบนโยบาย', fields: [{ key: 'policyName', label: 'ชื่อนโยบาย', required: true }, { key: 'policyVersion', label: 'เวอร์ชัน', required: true }, { key: 'signatureName', label: 'ชื่อสำหรับ e-sign', required: true }, { key: 'confirmed', label: 'ยืนยันว่าอ่านและรับทราบแล้ว', type: 'checkbox', required: true }] },
  ] },
  { domain: 'evidence', label: 'Audit Evidence Center', shortLabel: 'หลักฐาน', description: 'สุขภาพมาตรการควบคุมและทะเบียนหลักฐานรวม; PDF Designer เลื่อนไปหลัง Go-live', viewPermission: 'evidence.view', forms: [] },
  { domain: 'audit-management', label: 'Audit Management', shortLabel: 'Audit', description: 'แผนตรวจ ข้อตรวจพบ แผนแก้ไข และ independent closure verification', viewPermission: 'audit_management.view', managePermission: 'audit_management.manage', forms: [
    { entity: 'audits', label: 'เพิ่มงานตรวจ', fields: [{ key: 'title', label: 'ชื่องานตรวจ', required: true }, { key: 'auditType', label: 'ประเภทการตรวจ' }, { key: 'scope', label: 'ขอบเขต', type: 'textarea', required: true }, { key: 'criteria', label: 'เกณฑ์การตรวจ', type: 'textarea' }, { key: 'leadAuditor', label: 'Lead auditor' }, { key: 'auditee', label: 'หน่วยรับตรวจ' }, { key: 'plannedStart', label: 'เริ่ม', type: 'date' }, { key: 'plannedEnd', label: 'สิ้นสุด', type: 'date' }, status(['เปิด', 'กำลังวิเคราะห์', 'กำลังแก้ไข', 'รอตรวจยืนยัน', 'ปิด']), notes] },
    { entity: 'findings', label: 'เพิ่มข้อตรวจพบ', fields: [{ key: 'auditId', label: 'UUID งานตรวจ', required: true }, { key: 'title', label: 'หัวข้อ', required: true }, { key: 'findingType', label: 'ประเภท', type: 'select', options: ['ข้อไม่สอดคล้องร้ายแรง', 'ข้อไม่สอดคล้องเล็กน้อย', 'ข้อสังเกต', 'โอกาสปรับปรุง'] }, { key: 'requirement', label: 'ข้อกำหนด', type: 'textarea' }, { key: 'evidence', label: 'หลักฐานที่พบ', type: 'textarea' }, { key: 'rootCause', label: 'Root cause', type: 'textarea' }, { key: 'actionPlan', label: 'Action plan', type: 'textarea' }, { key: 'owner', label: 'เจ้าของแผน', required: true }, { key: 'dueDate', label: 'Due date', type: 'date' }, status(['เปิด', 'กำลังวิเคราะห์', 'กำลังแก้ไข', 'รอตรวจยืนยัน', 'ปิด']), notes] },
  ] },
  { domain: 'documents', label: 'Governance Documents', shortLabel: 'เอกสาร', description: 'คลัง metadata เอกสารนโยบาย มาตรฐาน คู่มือ และเวอร์ชันที่อนุมัติ', viewPermission: 'governance_document.view', managePermission: 'governance_document.manage', forms: [
    { entity: 'documents', label: 'ลงทะเบียนเอกสาร', fields: [{ key: 'documentCode', label: 'รหัสเอกสาร', required: true }, { key: 'title', label: 'ชื่อเอกสาร', required: true }, { key: 'documentType', label: 'ประเภท', type: 'select', options: ['นโยบาย', 'มาตรฐาน', 'ขั้นตอนปฏิบัติ', 'คู่มือ', 'แบบฟอร์ม', 'รายงาน'] }, { key: 'version', label: 'เวอร์ชัน', required: true }, { key: 'owner', label: 'Document owner' }, { key: 'approvedBy', label: 'ผู้อนุมัติ' }, { key: 'effectiveDate', label: 'วันที่มีผล', type: 'date' }, { key: 'reviewDate', label: 'วันทบทวน', type: 'date' }, { key: 'documentUrl', label: 'URL เอกสาร HTTPS', type: 'url', required: true }, status(['ร่าง', 'รออนุมัติ', 'ใช้งาน', 'ยกเลิก', 'แทนที่แล้ว']), notes] },
  ] },
  { domain: 'operations', label: 'Operations Hardening', shortLabel: 'Hardening', description: 'Retention run, Joiner/Mover/Leaver และสถานะ operational controls', viewPermission: 'operations.view', managePermission: 'operations.manage', forms: [
    { entity: 'employee-lifecycle', label: 'เริ่ม JML Checklist', fields: [{ key: 'employeeId', label: 'UUID พนักงาน', required: true }, { key: 'eventType', label: 'เหตุการณ์', type: 'select', options: ['JOINER', 'MOVER', 'LEAVER'], required: true }, { key: 'effectiveDate', label: 'วันที่มีผล', type: 'date', required: true }, { key: 'newDepartment', label: 'หน่วยงานใหม่' }, { key: 'newPosition', label: 'ตำแหน่งใหม่' }, { key: 'reason', label: 'เหตุผล', type: 'textarea' }, notes] },
  ] },
  { domain: 'integrations', label: 'Integration Outbox', shortLabel: 'Outbox', description: 'ติดตาม idempotent jobs, retry/dead-letter และ provenance ของรายการข้ามโมดูล', viewPermission: 'integration.view', managePermission: 'integration.manage', forms: [] },
];

export const governanceSearchText = (record: GovernanceRecord) => [record.code, record.title, record.subtitle, record.status, record.owner, ...record.details.map((item) => item.value)].join(' ').toLocaleLowerCase('th');

