import { z } from 'zod';

const text = (max: number) => z.string().trim().max(max).default('');
const required = (max: number) => z.string().trim().min(1).max(max);
const optionalDate = z.union([z.string().date(), z.literal('')]).default('');
const optionalUrl = z.union([z.string().trim().url().max(1000).refine((value) => value.startsWith('https://'), 'ต้องเป็น HTTPS'), z.literal('')]).default('');
const uuid = z.string().uuid();
const notes = text(2000);

export const governanceCreateSchemas: Record<string, z.ZodTypeAny> = {
  'data-classification/data-assets': z.object({ dataName: required(200), systemName: required(200), classification: z.enum(['ลับมาก', 'ลับ', 'ไม่ลับ']), dataOwner: required(200), custodian: text(200), storageMethod: text(500), retentionDays: z.number().int().min(1).max(36500).optional(), containsPersonalData: z.boolean().default(false), status: z.enum(['ใช้งาน', 'ระงับ', 'ยกเลิก']).default('ใช้งาน'), notes }),
  'data-classification/destruction-requests': z.object({ dataAssetId: uuid, reason: required(2000) }),
  'compliance/laws': z.object({ lawName: required(300), shortName: text(100), authority: text(200), version: text(100), effectiveDate: optionalDate, applicabilityStatus: z.enum(['ใช้บังคับ', 'ใช้เป็นกรอบ', 'ต้องยืนยัน', 'ไม่เกี่ยวข้อง']), owner: text(200), sourceUrl: optionalUrl, status: z.enum(['ใช้งาน', 'รอทบทวน', 'ยกเลิก']).default('ใช้งาน'), notes }),
  'compliance/obligations': z.object({ lawId: uuid, clause: text(200), requirement: required(4000), controlDomain: text(200), controlOwner: text(200), frequency: text(100), evidenceRequired: z.boolean().default(true), relatedModule: text(100), applicabilityStatus: z.enum(['ใช้บังคับ', 'ใช้เป็นกรอบ', 'ต้องยืนยัน', 'ไม่เกี่ยวข้อง']).default('ใช้บังคับ'), dueDate: optionalDate, status: z.enum(['เปิด', 'พักใช้', 'ปิด']).default('เปิด'), notes }),
  'compliance/assessments': z.object({ obligationId: uuid, assessmentDate: z.string().date(), result: z.enum(['สอดคล้อง', 'สอดคล้องบางส่วน', 'ไม่สอดคล้อง', 'ไม่เกี่ยวข้อง']), controlDescription: text(4000), evidenceUrl: optionalUrl, gapDescription: text(4000), nextReviewDue: optionalDate, notes }),
  'compliance/corrective-actions': z.object({ obligationId: uuid, assessmentId: z.union([uuid, z.literal('')]).default(''), title: required(300), rootCause: text(4000), actionPlan: required(4000), owner: required(200), priority: z.enum(['วิกฤต', 'สูง', 'ปานกลาง', 'ต่ำ']).default('ปานกลาง'), dueDate: optionalDate, status: z.enum(['เปิด', 'กำลังดำเนินการ', 'รอตรวจสอบ', 'เสร็จสิ้น', 'ยกเลิก']).default('เปิด'), notes }),
  'privacy/ropa': z.object({ processName: required(300), department: required(200), dataOwner: text(200), purpose: required(4000), lawfulBasis: z.enum(['ความยินยอม', 'สัญญา', 'หน้าที่ตามกฎหมาย', 'ประโยชน์สำคัญต่อชีวิต', 'ภารกิจเพื่อประโยชน์สาธารณะ', 'ประโยชน์โดยชอบด้วยกฎหมาย']), dataSubjects: text(2000), personalData: text(4000), sensitiveData: text(4000), recipients: text(2000), crossBorderTransfer: z.boolean().default(false), retentionPeriod: text(500), securityMeasures: text(4000), dpiaRequired: z.boolean().default(false), dpiaStatus: text(100), reviewDate: optionalDate, status: z.enum(['ร่าง', 'ใช้งาน', 'รอทบทวน', 'ยกเลิก']).default('ร่าง'), notes }),
  'privacy/consents': z.object({ dataSubjectRef: required(200), purpose: required(1000), noticeVersion: required(100), channel: required(100), grantedAt: z.string().date(), evidenceUrl: optionalUrl, notes }),
  'privacy/dsr': z.object({ requestType: z.enum(['ขอเข้าถึงข้อมูล', 'ขอสำเนาข้อมูล', 'ขอแก้ไขข้อมูล', 'ขอลบข้อมูล', 'ขอระงับการใช้', 'ขอคัดค้าน', 'ขอโอนย้ายข้อมูล', 'ถอนความยินยอม']), dataSubjectRef: required(200), contact: required(300), owner: text(200), status: z.enum(['รับคำขอ', 'รอยืนยันตัวตน', 'กำลังดำเนินการ', 'รอข้อมูลเพิ่มเติม', 'เสร็จสิ้น', 'ปฏิเสธ']).default('รับคำขอ'), notes }),
  'risk/risks': z.object({ title: required(300), category: text(100), relatedAsset: text(200), relatedSystem: text(200), threat: text(4000), vulnerability: text(4000), owner: required(200), likelihood: z.number().int().min(1).max(5), impact: z.number().int().min(1).max(5), treatment: text(100), existingControls: text(4000), treatmentPlan: text(4000), treatmentOwner: text(200), dueDate: optionalDate, residualLikelihood: z.number().int().min(1).max(5).optional(), residualImpact: z.number().int().min(1).max(5).optional(), status: z.enum(['เปิด', 'กำลังจัดการ', 'เฝ้าระวัง', 'ปิด']).default('เปิด'), notes }),
  'ai-cloud/ai-tools': z.object({ toolName: required(200), vendor: text(200), purpose: text(2000), allowedDataTypes: text(2000), prohibitedDataTypes: required(2000), owner: text(200), approvalRef: text(200), status: z.enum(['รออนุมัติ', 'อนุมัติ', 'ระงับ', 'ยกเลิก']).default('รออนุมัติ'), notes }),
  'ai-cloud/cloud-services': z.object({ serviceName: required(200), provider: required(200), purpose: text(2000), allowedDataClass: z.enum(['ไม่ลับ', 'ลับ', 'ลับมาก']).default('ไม่ลับ'), owner: text(200), approvalRef: text(200), backupArrangement: text(2000), exitPlan: required(4000), contractExpiry: optionalDate, status: z.enum(['รออนุมัติ', 'ใช้งาน', 'ระงับ', 'ยกเลิก']).default('รออนุมัติ'), notes }),
  'awareness/training-plans': z.object({ year: z.number().int().min(2020).max(2200), quarter: z.enum(['Q1', 'Q2', 'Q3', 'Q4']), topic: required(300), targetGroup: text(500), plannedDate: optionalDate, responsible: text(200), passingScore: z.number().min(0).max(100).default(80), status: z.enum(['วางแผน', 'เปิดลงทะเบียน', 'กำลังดำเนินการ', 'เสร็จสิ้น', 'ยกเลิก']).default('วางแผน'), notes }),
  'awareness/acknowledgements': z.object({ policyName: required(300), policyVersion: required(100), signatureName: required(200), confirmed: z.literal(true) }),
  'audit-management/audits': z.object({ title: required(300), auditType: text(100), scope: required(4000), criteria: text(4000), leadAuditor: text(200), auditee: text(500), plannedStart: optionalDate, plannedEnd: optionalDate, status: z.enum(['เปิด', 'กำลังวิเคราะห์', 'กำลังแก้ไข', 'รอตรวจยืนยัน', 'ปิด']).default('เปิด'), notes }),
  'audit-management/findings': z.object({ auditId: uuid, title: required(300), findingType: text(100), requirement: text(4000), evidence: text(4000), rootCause: text(4000), actionPlan: text(4000), owner: required(200), dueDate: optionalDate, status: z.enum(['เปิด', 'กำลังวิเคราะห์', 'กำลังแก้ไข', 'รอตรวจยืนยัน', 'ปิด']).default('เปิด'), notes }),
  'documents/documents': z.object({ documentCode: z.string().trim().min(2).max(100).regex(/^[A-Za-z0-9._/-]+$/), title: required(300), documentType: text(100), version: required(100), owner: text(200), approvedBy: text(200), effectiveDate: optionalDate, reviewDate: optionalDate, documentUrl: optionalUrl.refine((value) => Boolean(value), 'กรุณาระบุ URL เอกสาร'), status: z.enum(['ร่าง', 'รออนุมัติ', 'ใช้งาน', 'ยกเลิก', 'แทนที่แล้ว']).default('ร่าง'), notes }),
  'operations/employee-lifecycle': z.object({ employeeId: uuid, eventType: z.enum(['JOINER', 'MOVER', 'LEAVER']), effectiveDate: z.string().date(), newDepartment: text(200), newPosition: text(200), reason: text(2000), notes }),
};

export const governanceActionSchema = z.object({ comment: text(2000).optional(), method: text(500).optional(), evidenceUrl: optionalUrl.optional() }).passthrough();

