import type { FormModuleKey } from '../../types/forms';

const fieldClass = 'mt-1 min-h-9 w-full rounded-lg border border-slate-300 bg-white px-2 py-1.5 text-sm text-slate-900 outline-none focus:border-primary-500 dark:border-slate-600 dark:bg-slate-900 dark:text-white';
const sourceLabels: Record<FormModuleKey, string> = { ticket: 'Ticket', incident: 'Incident', change: 'Change', contract: 'Contract', audit: 'Audit', risk: 'Risk', service_request: 'Service Request', asset_borrow: 'Asset Borrow', custom: 'Custom' };

export function GenericLinkPanel({ module, recordId, sources, onChange, readOnly = false }: { module: FormModuleKey; recordId: string; sources?: Record<string, Array<Record<string, string | null>>>; onChange: (module: FormModuleKey, recordId: string) => void; readOnly?: boolean }) {
  const options = sources?.[module] ?? [];
  return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800" data-testid="generic-link-panel"><div className="flex items-center gap-2 font-bold text-slate-900 dark:text-white">Generic Link <span className="text-xs font-normal text-slate-500">source_module + source_record_id</span></div><p className="mt-1 text-xs text-slate-500">แบบฟอร์มเดียวกันใช้ได้กับ Incident, Change, Contract, Audit, Risk, Service Request และ Ticket</p><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs font-semibold">Source module<select value={module} disabled={readOnly} onChange={(event) => onChange(event.target.value as FormModuleKey, '')} className={fieldClass}>{(Object.keys(sourceLabels) as FormModuleKey[]).map((key) => <option key={key} value={key}>{sourceLabels[key]}</option>)}</select></label><label className="text-xs font-semibold">Source record{options.length ? <select value={recordId} disabled={readOnly} onChange={(event) => onChange(module, event.target.value)} className={fieldClass}><option value="">— เลือก Record —</option>{options.map((option) => { const label = option.ticket_no ?? option.incident_number ?? option.change_number ?? option.contract_number ?? option.audit_code ?? option.risk_code ?? option.service_code ?? option.id ?? ''; const title = option.title ?? option.name ?? option.summary ?? option.service_name ?? ''; return <option key={option.id ?? label} value={option.id ?? ''}>{label}{title ? ` · ${title}` : ''}</option>; })}</select> : <input value={recordId} disabled={readOnly} onChange={(event) => onChange(module, event.target.value)} className={fieldClass} placeholder="UUID หรือรหัสของ Record" />}</label></div></section>;
}
